title: Jack Walker
description: Biomedical Engineering student at King's College London, interested in statistics, machine learning, and their applications to healthcare and finance.
theme: jekyll-theme-cayman
markdown: kramdown
show_downloads: false
